
#ifndef _RESOURCE_INC
#define _RESOURCE_INC

#include <Windows.h>

#define IDM_FILE_NEW				101
#define IDM_FILE_OPEN				102
#define IDM_FILE_SAVE_AS			103
#define IDM_FILE_CLOSE				104
#define IDM_FILE_EXIT				105
#define IDM_EDIT_CLEAR				106
#define IDM_EDIT_GENERATE_MAZE		107
#define IDM_EDIT_GENERATE_RANDOM	108
#define IDM_DISPLAY_SHOWWORK		109
#define IDM_HELP_HOWTOUSE			110

#define IDT_NEW_WIDTH				111
#define IDT_NEW_HEIGHT				112
#define IDB_NEW_CREATE				113
#define IDB_NEW_CANCEL				114
#define IDCB_METHOD					115
#define IDCB_ILLUSTRATE				116

#define IDB_COMPUTE_PATH			117
#define IDB_REDRAW					118

#define IDB_CLOSE_HOWTOUSE			119

#endif /* _RESOURCE_INC */